import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.169.0/build/three.module.js';

const mount=document.getElementById('game'), mission=document.getElementById('mission'), hint=document.getElementById('hint'), loading=document.getElementById('loading'), fade=document.getElementById('fade');
const dialog=document.getElementById('dialog'), dialogTitle=document.getElementById('dialogTitle'), dialogText=document.getElementById('dialogText'), answers=document.getElementById('answers');

const scene=new THREE.Scene(); scene.background=new THREE.Color(0x9ecbf0); scene.fog=new THREE.Fog(0x9ecbf0,22,70);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,200); camera.position.set(-8,5.6,10);
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; mount.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xd8ecff,0x4c5662,2.2)); const sun=new THREE.DirectionalLight(0xffffff,2.2); sun.position.set(-10,18,8); sun.castShadow=true; sun.shadow.mapSize.set(2048,2048); scene.add(sun);

const world=new THREE.Group(); scene.add(world); let room='outside', targetDoor=null, actionReady=false, locked=false, walkT=0;
const keys={}; addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE')interact()}); addEventListener('keyup',e=>keys[e.code]=false);
for(const [id,code] of [['left','ArrowLeft'],['right','ArrowRight']]){const b=document.getElementById(id);b.onpointerdown=()=>keys[code]=true;b.onpointerup=b.onpointerleave=()=>keys[code]=false} document.getElementById('action').onclick=interact;

function mat(c,rough=.8){return new THREE.MeshStandardMaterial({color:c,roughness:rough})}
function box(w,h,d,c,x,y,z){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;world.add(m);return m}
function textSprite(text,bg='#0b2f67'){const cv=document.createElement('canvas');cv.width=512;cv.height=128;const c=cv.getContext('2d');c.fillStyle=bg;c.fillRect(0,0,512,128);c.fillStyle='#fff';c.font='700 38px Arial';c.textAlign='center';c.textBaseline='middle';c.fillText(text,256,64);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(cv)}));s.scale.set(5,1.25,1);return s}
function human(suit=0x173f78,skin=0xd6a06d){const g=new THREE.Group();const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.42,.95,6,12),mat(suit));torso.position.y=1.45;const head=new THREE.Mesh(new THREE.SphereGeometry(.34,20,20),mat(skin));head.position.y=2.35;const legL=new THREE.Mesh(new THREE.CapsuleGeometry(.14,.85,5,10),mat(0x1c2738));const legR=legL.clone();legL.position.set(-.2,.55,0);legR.position.set(.2,.55,0);const armL=new THREE.Mesh(new THREE.CapsuleGeometry(.12,.78,5,10),mat(skin));const armR=armL.clone();armL.position.set(-.56,1.5,0);armR.position.set(.56,1.5,0);g.add(torso,head,legL,legR,armL,armR);g.userData={legL,legR,armL,armR};g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});return g}
const player=human();scene.add(player);

function clearWorld(){while(world.children.length)world.remove(world.children[0]);targetDoor=null;actionReady=false}
function ground(c=0xaab4bf){box(60,.35,24,c,0,-.2,0)}
function buildOutside(){clearWorld();room='outside';mission.textContent='მისია: მიდი საკონსულოს მთავარ კართან';scene.background.set(0x9ecbf0);ground(0xb5bec7);box(60,.08,7,0x343a43,0,.05,7);for(let x=-26;x<26;x+=5)box(2,.03,.18,0xffffff,x,.1,7);
box(17,8,7,0xe8edf2,10,4,-2);box(4.2,5.1,.5,0x17395f,10,2.55,1.7);for(const x of [4.5,7.5,12.5,15.5])box(.6,6,.6,0xffffff,x,3,-.1);const sign=textSprite('U.S. EMBASSY');sign.position.set(10,7.2,1.6);world.add(sign);box(.13,7,.13,0x555b66,18,3.5,1);box(2.8,1.6,.12,0xb22234,16.7,6.2,1);const guard=human(0x244d86);guard.position.set(6.5,0,1.2);world.add(guard);for(let i=0;i<4;i++){const p=human(i%2?0x4b5563:0x6b3f2a);p.scale.set(.85,.85,.85);p.position.set(-5+i*2.2,0,1.4+(i%2)*.5);world.add(p)}player.position.set(-18,0,2);targetDoor=new THREE.Vector3(10,0,1.8);camera.position.set(-12,5.8,12)}
function buildSecurity(){clearWorld();room='security';mission.textContent='მისია: დაელაპარაკე დაცვას და გაიარე შემოწმება';scene.background.set(0xdce5ef);ground(0xc6ced8);box(28,7,.4,0xf4f6f8,0,3.5,-6);box(.4,7,18,0xf4f6f8,-14,3.5,0);box(.4,7,18,0xf4f6f8,14,3.5,0);const s=textSprite('SECURITY CHECK','#374b63');s.position.set(0,6,-5.7);world.add(s);const guard=human(0x244d86);guard.position.set(-3,0,-1);world.add(guard);box(.5,4,.5,0x364152,3,2,-1);box(.5,4,.5,0x364152,6,2,-1);box(3.5,.5,.5,0x364152,4.5,4,-1);box(4,3.6,1.7,0x7a8796,10,1.8,-2);player.position.set(-11,0,2);targetDoor=new THREE.Vector3(-3,0,-1);camera.position.set(-8,6,12)}
function buildDocuments(){clearWorld();room='documents';mission.textContent='მისია: მიაწოდე ფოტო, DS-160 და ქვითარი';ground(0xc5ccd5);box(28,7,.4,0xf3f5f7,0,3.5,-6);box(12,2.1,2.2,0x75482d,4,1.05,-1.5);box(12,4,.25,0xaed0e8,4,4,-.3);const clerk=human(0x3f628d);clerk.position.set(4,1.9,-2);world.add(clerk);['5×5 PHOTO','DS-160','RECEIPT'].forEach((t,i)=>{const sp=textSprite(t,'#ffffff');sp.material.map.image.getContext?.;sp.position.set(-8+i*3.1,1.4,1);sp.scale.set(2.7,.75,1);world.add(sp)});player.position.set(-11,0,2);targetDoor=new THREE.Vector3(4,0,0);camera.position.set(-7,6,12)}
function buildWaiting(){clearWorld();room='waiting';mission.textContent='მისია: ჩადგი რიგში — შენს წინ ერთი აპლიკანტია';ground(0xc4ccd6);box(28,7,.4,0xf3f5f7,0,3.5,-6);for(let r=0;r<2;r++)for(let i=0;i<4;i++){box(1.5,.18,1.4,0x37516f,-7+i*2,1,-2+r*2);box(.18,1.1,1.4,0x26394f,-7+i*2,.5,-2+r*2)}const board=textSprite('A-023  →  WINDOW 4','#111827');board.position.set(3,5.5,-5.7);world.add(board);const ahead=human(0x5d4037);ahead.position.set(6,0,-1);world.add(ahead);player.position.set(-10,0,2);targetDoor=new THREE.Vector3(5,0,-1);camera.position.set(-7,6,13)}
function buildInterview(){clearWorld();room='interview';mission.textContent='ინტერვიუ დაიწყო — უპასუხე კონსულის კითხვებს';ground(0xbec7d1);box(30,7,.4,0xe8edf2,0,3.5,-7);for(let x=-10;x<=10;x+=10){box(8,2.3,2.2,0x6f452c,x,1.15,-1.8);box(8,4,.2,0xaed0e8,x,4,-.5);const c=human(0x2f5687);c.position.set(x,1.9,-2.2);world.add(c)}const applicant=human(0x3b4c62);applicant.position.set(-8,0,2);world.add(applicant);player.position.set(0,0,2);targetDoor=new THREE.Vector3(0,0,0);camera.position.set(-1,5.2,10);setTimeout(()=>showDialog('კონსული','დილა მშვიდობისა. რა მიზნით მიდიხართ ამერიკაში?',['10-დღიანი ტურისტული მოგზაურობა','მეგობრის მონახულება და მოგზაურობა','საქმიანი შეხვედრები','იქ დარჩენის შესაძლებლობის ნახვა']),600)}
function showDialog(title,text,opts){locked=true;dialogTitle.textContent=title;dialogText.textContent=text;answers.innerHTML='';opts.forEach(o=>{const b=document.createElement('button');b.className='answer';b.textContent=o;b.onclick=()=>{dialog.classList.remove('show');locked=false;if(room==='interview')setTimeout(()=>showDialog('კონსული','რას საქმიანობთ საქართველოში?',['ვარ დასაქმებული','ვარ თვითდასაქმებული','ამჟამად უმუშევარი ვარ','საქმიანობა ჯერ არ მაქვს განსაზღვრული']),350)};answers.appendChild(b)});dialog.classList.add('show')}
function interact(){if(!actionReady||locked)return;if(room==='outside')transition(buildSecurity);else if(room==='security')showDialog('დაცვის თანამშრომელი','გაქვთ ტელეფონი, ჭკვიანი საათი, გასაღები, ყურსასმენი ან სხვა ელექტრონული ნივთი?',['დიახ — ნივთებს ლოკერში დავტოვებ','არა — აკრძალული ნივთი არ მაქვს']);else if(room==='documents')transition(buildWaiting);else if(room==='waiting')transition(buildInterview)}
function transition(next){locked=true;fade.classList.add('show');setTimeout(()=>{next();fade.classList.remove('show');locked=false},380)}

function animate(t){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04);if(!locked){let dx=0,dz=0;if(keys.KeyA||keys.ArrowLeft)dx-=1;if(keys.KeyD||keys.ArrowRight)dx+=1;if(keys.KeyW||keys.ArrowUp)dz-=1;if(keys.KeyS||keys.ArrowDown)dz+=1;const moving=dx||dz;if(moving){const len=Math.hypot(dx,dz);dx/=len;dz/=len;player.position.x+=dx*5*dt;player.position.z+=dz*5*dt;player.rotation.y=Math.atan2(dx,dz);walkT+=dt*10}else walkT=0;const u=player.userData;u.legL.rotation.x=Math.sin(walkT)*.65;u.legR.rotation.x=-Math.sin(walkT)*.65;u.armL.rotation.x=-Math.sin(walkT)*.55;u.armR.rotation.x=Math.sin(walkT)*.55;player.position.y=Math.abs(Math.sin(walkT*2))*.035;camera.position.x+=(player.position.x-4-camera.position.x)*.035;camera.lookAt(player.position.x+2,1.6,player.position.z-1)}actionReady=targetDoor?player.position.distanceTo(targetDoor)<3:false;hint.textContent=actionReady?'დააჭირე E — მოქმედება':'WASD / ისრები — მოძრაობა • E — მოქმედება';renderer.render(scene,camera)}
const clock=new THREE.Clock();buildOutside();loading.classList.add('hide');animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
