(() => {
const mount=document.getElementById('game'),loading=document.getElementById('loading'),mission=document.getElementById('mission'),hint=document.getElementById('hint'),fade=document.getElementById('fade'),dialog=document.getElementById('dialog'),dialogTitle=document.getElementById('dialogTitle'),dialogText=document.getElementById('dialogText'),answers=document.getElementById('answers'),errorBox=document.getElementById('error');
try{
if(!window.THREE)throw new Error('Three.js ვერ ჩაიტვირთა');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9ecbf0);scene.fog=new THREE.Fog(0x9ecbf0,28,85);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,250);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;mount.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xdcecff,0x53606f,2.4));const sun=new THREE.DirectionalLight(0xffffff,2.6);sun.position.set(-14,22,12);sun.castShadow=true;scene.add(sun);
const world=new THREE.Group();scene.add(world);const clock=new THREE.Clock(),keys={};let room='outside',target=new THREE.Vector3(11,0,2),locked=false,actionReady=false,walkT=0;
const mat=(c,r=.82)=>new THREE.MeshStandardMaterial({color:c,roughness:r});
function box(w,h,d,c,x,y,z){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;world.add(m);return m}
function human(suit=0x173f78,skin=0xd6a06d){const g=new THREE.Group();const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.42,.95,6,12),mat(suit));torso.position.y=1.45;const head=new THREE.Mesh(new THREE.SphereGeometry(.34,20,20),mat(skin));head.position.y=2.35;const legL=new THREE.Mesh(new THREE.CapsuleGeometry(.14,.85,5,10),mat(0x1c2738)),legR=legL.clone();legL.position.set(-.2,.55,0);legR.position.set(.2,.55,0);const armL=new THREE.Mesh(new THREE.CapsuleGeometry(.12,.78,5,10),mat(skin)),armR=armL.clone();armL.position.set(-.56,1.5,0);armR.position.set(.56,1.5,0);g.add(torso,head,legL,legR,armL,armR);g.userData={legL,legR,armL,armR};g.traverse(o=>{if(o.isMesh){o.castShadow=o.receiveShadow=true}});return g}
function sign(text,x,y,z,bg='#0b2f67'){const cv=document.createElement('canvas');cv.width=1024;cv.height=220;const c=cv.getContext('2d');c.fillStyle=bg;c.fillRect(0,0,1024,220);c.fillStyle='#fff';c.font='700 64px Arial';c.textAlign='center';c.textBaseline='middle';c.fillText(text,512,110);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(cv)}));s.scale.set(7.5,1.65,1);s.position.set(x,y,z);world.add(s)}
const player=human();scene.add(player);
function clearWorld(){while(world.children.length)world.remove(world.children[0])}
function ground(c=0xb7c0c9){box(70,.35,28,c,0,-.2,0)}
function buildOutside(){clearWorld();room='outside';mission.textContent='მისია: მიდი საკონსულოს მთავარ კართან';scene.background.set(0x9ecbf0);ground();box(70,.08,8,0x3d444e,0,.05,8);for(let x=-32;x<32;x+=6)box(2.5,.03,.18,0xffffff,x,.1,8);box(19,9,8,0xe9edf2,11,4.5,-2);box(4.4,5.3,.6,0x17395f,11,2.65,2.05);for(const x of [4.8,8,14,17.2])box(.72,6.4,.72,0xffffff,x,3.2,-.1);sign('U.S. EMBASSY',11,7.8,2.15);box(.14,8,.14,0x555b66,20,4,1);box(3.3,1.8,.12,0xb22234,18.4,7,1);const guard=human(0x244d86);guard.position.set(7.2,0,1.3);world.add(guard);for(let i=0;i<4;i++){const p=human(i%2?0x4b5563:0x6b3f2a);p.scale.setScalar(.86);p.position.set(-5+i*2.5,0,1.5);world.add(p)}player.position.set(-19,0,2.2);target.set(11,0,2);camera.position.set(-11,5.8,12)}
function buildSecurity(){clearWorld();room='security';mission.textContent='მისია: დაელაპარაკე დაცვას და გაიარე შემოწმება';scene.background.set(0xdfe7ef);ground(0xc6ced8);box(30,8,.5,0xf4f6f8,0,4,-7);box(.5,8,20,0xf4f6f8,-15,4,0);box(.5,8,20,0xf4f6f8,15,4,0);sign('SECURITY CHECK',0,6.7,-6.6,'#374b63');const guard=human(0x244d86);guard.position.set(-3,0,-1);world.add(guard);box(.55,4.4,.55,0x364152,3,2.2,-1);box(.55,4.4,.55,0x364152,6,2.2,-1);box(3.6,.5,.55,0x364152,4.5,4.2,-1);box(4.2,3.8,1.8,0x7a8796,10,1.9,-2);player.position.set(-11,0,2);target.set(-3,0,-1);camera.position.set(-8,6,12)}
function buildDocuments(){clearWorld();room='documents';mission.textContent='მისია: მიაწოდე ფოტო, DS-160 და ქვითარი';scene.background.set(0xdfe7ef);ground(0xc5ccd5);box(30,8,.5,0xf3f5f7,0,4,-7);box(13,2.2,2.4,0x75482d,4,1.1,-1.7);box(13,4.3,.25,0xaed0e8,4,4.1,-.4);const clerk=human(0x3f628d);clerk.position.set(4,1.95,-2.2);world.add(clerk);sign('DOCUMENTS WINDOW',4,6,-6.5,'#374b63');player.position.set(-11,0,2);target.set(4,0,0);camera.position.set(-7,6,12)}
function buildWaiting(){clearWorld();room='waiting';mission.textContent='მისია: ჩადგი რიგში — შენს წინ ერთი აპლიკანტია';scene.background.set(0xdfe7ef);ground(0xc4ccd6);box(30,8,.5,0xf3f5f7,0,4,-7);for(let r=0;r<2;r++)for(let i=0;i<4;i++){box(1.5,.18,1.4,0x37516f,-7+i*2,1,-2+r*2);box(.18,1.1,1.4,0x26394f,-7+i*2,.5,-2+r*2)}sign('A-023 → WINDOW 4',3,5.8,-6.5,'#111827');const ahead=human(0x5d4037);ahead.position.set(6,0,-1);world.add(ahead);player.position.set(-10,0,2);target.set(5.5,0,-1);camera.position.set(-7,6,13)}
function buildInterview(){clearWorld();room='interview';mission.textContent='ინტერვიუ დაიწყო — უპასუხე კონსულის კითხვებს';scene.background.set(0xd9e2eb);ground(0xbec7d1);box(32,8,.5,0xe8edf2,0,4,-8);for(let x=-10;x<=10;x+=10){box(8,2.4,2.4,0x6f452c,x,1.2,-1.9);box(8,4.4,.22,0xaed0e8,x,4.2,-.55);const c=human(0x2f5687);c.position.set(x,2,-2.3);world.add(c)}const applicant=human(0x3b4c62);applicant.position.set(-8,0,2);world.add(applicant);player.position.set(0,0,2);target.set(0,0,0);camera.position.set(-1,5.2,10);setTimeout(()=>showDialog('კონსული','დილა მშვიდობისა. რა მიზნით მიდიხართ ამერიკაში?',['10-დღიანი ტურისტული მოგზაურობა','მეგობრის მონახულება და მოგზაურობა','საქმიანი შეხვედრები','იქ დარჩენის შესაძლებლობის ნახვა']),500)}
function showDialog(title,text,opts){locked=true;dialogTitle.textContent=title;dialogText.textContent=text;answers.innerHTML='';opts.forEach(o=>{const b=document.createElement('button');b.className='answer';b.textContent=o;b.onclick=()=>{dialog.classList.remove('show');locked=false};answers.appendChild(b)});dialog.classList.add('show')}
function transition(next){locked=true;fade.classList.add('show');setTimeout(()=>{next();fade.classList.remove('show');locked=false},360)}
function interact(){if(!actionReady||locked)return;if(room==='outside')transition(buildSecurity);else if(room==='security')showDialog('დაცვის თანამშრომელი','გაქვთ ტელეფონი, ჭკვიანი საათი, გასაღები, ყურსასმენი ან სხვა ელექტრონული ნივთი?',['დიახ — ნივთებს ლოკერში დავტოვებ','არა — აკრძალული ნივთი არ მაქვს']);else if(room==='documents')transition(buildWaiting);else if(room==='waiting')transition(buildInterview)}
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE')interact()});addEventListener('keyup',e=>keys[e.code]=false);[['left','ArrowLeft'],['right','ArrowRight']].forEach(([id,code])=>{const b=document.getElementById(id);b.onpointerdown=()=>keys[code]=true;b.onpointerup=b.onpointerleave=()=>keys[code]=false});document.getElementById('action').onclick=interact;
buildOutside();loading.classList.add('hide');
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04);if(!locked){let dx=0,dz=0;if(keys.KeyA||keys.ArrowLeft)dx--;if(keys.KeyD||keys.ArrowRight)dx++;if(keys.KeyW||keys.ArrowUp)dz--;if(keys.KeyS||keys.ArrowDown)dz++;if(dx||dz){const len=Math.hypot(dx,dz);dx/=len;dz/=len;player.position.x+=dx*5*dt;player.position.z+=dz*5*dt;player.rotation.y=Math.atan2(dx,dz);walkT+=dt*10}else walkT=0;const u=player.userData;u.legL.rotation.x=Math.sin(walkT)*.65;u.legR.rotation.x=-Math.sin(walkT)*.65;u.armL.rotation.x=-Math.sin(walkT)*.55;u.armR.rotation.x=Math.sin(walkT)*.55;player.position.y=Math.abs(Math.sin(walkT*2))*.035;camera.position.x+=(player.position.x-4-camera.position.x)*.035;camera.position.z+=(player.position.z+10-camera.position.z)*.035;camera.lookAt(player.position.x+2,1.6,player.position.z-1)}actionReady=player.position.distanceTo(target)<3;hint.textContent=actionReady?'დააჭირე E — მოქმედება':'WASD / ისრები — მოძრაობა • E — მოქმედება';renderer.render(scene,camera)}animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})
}catch(err){console.error(err);loading.classList.add('hide');errorBox.textContent='3D გარემო ვერ გაეშვა: '+(err.message||'უცნობი შეცდომა');errorBox.classList.add('show')}
})();