(() => {
const $=id=>document.getElementById(id), mount=$('game'),loading=$('loading'),mission=$('mission'),hint=$('hint'),fade=$('fade'),dialog=$('dialog'),dialogTitle=$('dialogTitle'),dialogText=$('dialogText'),answers=$('answers'),errorBox=$('error');
try{
if(!window.THREE||!THREE.GLTFLoader) throw new Error('3D ბიბლიოთეკა ვერ ჩაიტვირთა');
const scene=new THREE.Scene();scene.background=new THREE.Color(0xa7d2f0);scene.fog=new THREE.Fog(0xa7d2f0,35,120);
const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,300);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputEncoding=THREE.sRGBEncoding;mount.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xe8f4ff,0x52606f,1.8));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(-18,28,16);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
const world=new THREE.Group();scene.add(world);const clock=new THREE.Clock(),keys={};let player,mixer,walkAction,idleAction,room='outside',target=new THREE.Vector3(14,0,1.5),locked=false,actionReady=false,modelTemplate=null;
const loader=new THREE.GLTFLoader();
const material=(c,r=.72,m=.02)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});
function mesh(g,m,x,y,z){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;world.add(o);return o}
function box(w,h,d,c,x,y,z,r=.72,m=.02){return mesh(new THREE.BoxGeometry(w,h,d),material(c,r,m),x,y,z)}
function cyl(rt,rb,h,c,x,y,z){return mesh(new THREE.CylinderGeometry(rt,rb,h,28),material(c),x,y,z)}
function sign(text,x,y,z,bg='#0b2f67',scale=1){const cv=document.createElement('canvas');cv.width=1200;cv.height=230;const c=cv.getContext('2d');c.fillStyle=bg;c.fillRect(0,0,1200,230);c.fillStyle='#fff';c.font='700 68px Arial';c.textAlign='center';c.textBaseline='middle';c.fillText(text,600,115);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(cv)}));s.scale.set(8.5*scale,1.65*scale,1);s.position.set(x,y,z);world.add(s);return s}
function clearWorld(){while(world.children.length)world.remove(world.children[0])}
function ground(c=0xbfc8d2){box(90,.3,34,c,0,-.15,0)}
function addTree(x,z){cyl(.18,.24,3.2,0x6f4b2e,x,1.6,z);const crown=mesh(new THREE.SphereGeometry(1.25,24,18),material(0x3f7d45),x,3.6,z);crown.scale.y=1.25}
function addBench(x,z){box(3,.16,.65,0x755136,x,.9,z);box(3,.16,.65,0x755136,x,1.55,z+.45);box(.15,1.2,.15,0x303943,x-1.15,.55,z);box(.15,1.2,.15,0x303943,x+1.15,.55,z)}
function addWindow(x,y,z,w=2.2,h=2.6){box(w,h,.18,0x91b8d0,x,y,z,.2,.1);box(w+.18,.12,.24,0xffffff,x,y+h/2,z+.02);box(w+.18,.12,.24,0xffffff,x,y-h/2,z+.02);box(.12,h,.24,0xffffff,x-w/2,y,z+.02);box(.12,h,.24,0xffffff,x+w/2,y,z+.02)}
function cloneCharacter(x,z,scale=.85,rot=0){const c=THREE.SkeletonUtils.clone(modelTemplate);c.scale.setScalar(scale);c.position.set(x,0,z);c.rotation.y=rot;c.traverse(o=>{if(o.isMesh){o.castShadow=o.receiveShadow=true}});world.add(c);return c}
function setAnimation(name){if(!mixer)return;const next=name==='walk'?walkAction:idleAction;if(next&&!next.isRunning()){(name==='walk'?idleAction:walkAction)?.fadeOut(.18);next.reset().fadeIn(.18).play()}}
function buildOutside(){clearWorld();room='outside';mission.textContent='მისია: მიუახლოვდი საკონსულოს მთავარ შესასვლელს';scene.background.set(0xa7d2f0);scene.fog.color.set(0xa7d2f0);ground(0xc7cdd4);box(90,.05,9,0x333941,0,.04,10);for(let x=-42;x<42;x+=7)box(3,.025,.18,0xffffff,x,.08,10);box(28,10,9,0xe9edf2,15,5,-3);box(6.2,5.8,.55,0x193c63,15,2.9,1.45,.25,.15);for(const x of [4.5,9.2,20.8,25.5]){cyl(.55,.68,7.4,0xffffff,x,3.7,-.4);box(1.5,.45,1.5,0xd8dee6,x,.22,-.4)}sign('U.S. EMBASSY',15,8.7,1.7,'#123f73',1.05);for(const x of [7.2,11.8,18.2,22.8])addWindow(x,5.2,1.63,2.3,2.9);box(.18,9,.18,0x4b5563,29,4.5,1);for(let i=0;i<7;i++)box(4.4,.18,.08,i%2?0xffffff:0xb22234,26.8,8.2-i*.33,1.08);box(1.9,1.25,.09,0x3c3b6e,25.55,7.55,1.09);addTree(-8,0);addTree(-2,1);addBench(-5,3.4);for(let i=0;i<3;i++)cloneCharacter(-9+i*2.4,1.6,.78,i%2?Math.PI:0);cloneCharacter(10,1.2,.86,Math.PI/2);player.position.set(-24,0,2.5);target.set(15,0,1.5);camera.position.set(-18,5.8,13)}
function interiorShell(title){scene.background.set(0xdde7ef);scene.fog.color.set(0xdde7ef);ground(0xc9d0d7);box(34,8,.45,0xf1f3f6,0,4,-8);box(.45,8,24,0xe9edf1,-17,4,0);box(.45,8,24,0xe9edf1,17,4,0);box(34,.22,24,0xffffff,0,8,0);sign(title,0,6.7,-7.7,'#374b63',.82)}
function buildSecurity(){clearWorld();room='security';mission.textContent='მისია: დაელაპარაკე დაცვას და გაიარე უსაფრთხოების შემოწმება';interiorShell('SECURITY CHECK');cloneCharacter(-3,-1,.86,Math.PI);box(1.8,1.2,1.2,0x35475d,-3,.65,-2.1);for(const x of [4,7])box(.45,4.4,.45,0x3f4c5c,x,2.2,-1);box(3.5,.5,.5,0x3f4c5c,5.5,4.2,-1);box(4.2,3.8,1.8,0x788696,11,1.9,-2);sign('LOCKERS',11,4.4,-1.1,'#596777',.52);box(5.5,1.2,2.2,0x6d4a31,-9,.6,-2);player.position.set(-13,0,2.5);target.set(-3,0,-1);camera.position.set(-9,5.5,12)}
function buildDocuments(){clearWorld();room='documents';mission.textContent='მისია: ჩააბარე ფოტო, DS-160 და მოსაკრებლის ქვითარი';interiorShell('DOCUMENT INTAKE');box(13,2.3,2.6,0x72462e,4,1.15,-1.7);box(13,4.2,.18,0xaed0e8,4,4.15,-.38,.12,.05);cloneCharacter(4,-2.2,.84,0);for(let i=0;i<3;i++){const x=-8+i*3.1;box(2.3,.12,1.7,0xffffff,x,.95,1);sign(['5×5 PHOTO','DS-160','RECEIPT'][i],x,1.45,.08,'#ffffff',.33)}player.position.set(-13,0,2.8);target.set(4,0,0);camera.position.set(-8,5.4,12)}
function buildWaiting(){clearWorld();room='waiting';mission.textContent='მისია: ჩადგი რიგში — შენს წინ ერთი აპლიკანტია';interiorShell('VISA WAITING HALL');for(let r=0;r<3;r++)for(let i=0;i<5;i++){const x=-10+i*2.4,z=-4+r*2.3;box(1.55,.16,1.35,0x37516f,x,1,z);box(.16,1.1,1.35,0x26394f,x,.52,z)}sign('A-023  →  WINDOW 4',5,5.9,-7.7,'#111827',.8);cloneCharacter(7,-1,.84,Math.PI);cloneCharacter(-6,-3.5,.78,0);cloneCharacter(-1,-1.2,.78,Math.PI/2);player.position.set(-13,0,3.5);target.set(6.5,0,-1);camera.position.set(-9,6,14)}
function buildInterview(){clearWorld();room='interview';mission.textContent='ინტერვიუ დაიწყო — უპასუხე კონსულის კითხვებს';interiorShell('NONIMMIGRANT VISA INTERVIEW');for(let x=-11;x<=11;x+=11){box(8.8,2.5,2.6,0x6f452c,x,1.25,-2);box(8.8,4.4,.18,0xaed0e8,x,4.3,-.55,.12,.04);cloneCharacter(x,-2.5,.82,0)}cloneCharacter(-8,2,.8,Math.PI);cloneCharacter(8,2,.8,Math.PI);player.position.set(0,0,2.4);target.set(0,0,0);camera.position.set(-.5,4.7,9.5);setTimeout(()=>showDialog('კონსული','დილა მშვიდობისა. რა მიზნით მიდიხართ ამერიკაში?',['დაგეგმილი 10-დღიანი ტურისტული მოგზაურობა','ოჯახის წევრის მონახულება და მოგზაურობა','საქმიანი შეხვედრები','იქ დარჩენის შესაძლებლობის ნახვა']),650)}
function showDialog(title,text,opts){locked=true;dialogTitle.textContent=title;dialogText.textContent=text;answers.innerHTML='';opts.forEach((o,i)=>{const b=document.createElement('button');b.className='answer';b.textContent=o;b.onclick=()=>{dialog.classList.remove('show');locked=false;if(room==='interview')setTimeout(()=>showDialog('კონსული','რას საქმიანობთ საქართველოში?',['ვარ დასაქმებული და მაქვს სტაბილური შემოსავალი','ვარ თვითდასაქმებული','ამჟამად უმუშევარი ვარ','საქმიანობა ჯერ არ მაქვს განსაზღვრული']),350)};answers.appendChild(b)});dialog.classList.add('show')}
function interact(){if(!actionReady||locked)return;if(room==='outside')transition(buildSecurity);else if(room==='security')showDialog('დაცვის თანამშრომელი','გაქვთ ტელეფონი, ჭკვიანი საათი, ყურსასმენი, გასაღები ან სხვა ელექტრონული ნივთი?',['დიახ — ნივთებს ლოკერში დავტოვებ','არა — აკრძალული ნივთი არ მაქვს']);else if(room==='documents')transition(buildWaiting);else if(room==='waiting')transition(buildInterview)}
function transition(next){locked=true;fade.classList.add('show');setTimeout(()=>{next();fade.classList.remove('show');locked=false},420)}
function bindControls(){addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE')interact()});addEventListener('keyup',e=>keys[e.code]=false);for(const [id,code] of [['left','ArrowLeft'],['right','ArrowRight']]){const b=$(id);b.onpointerdown=()=>keys[code]=true;b.onpointerup=b.onpointerleave=()=>keys[code]=false}$('action').onclick=interact}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04);if(mixer)mixer.update(dt);if(player&&!locked){let dx=0,dz=0;if(keys.KeyA||keys.ArrowLeft)dx--;if(keys.KeyD||keys.ArrowRight)dx++;if(keys.KeyW||keys.ArrowUp)dz--;if(keys.KeyS||keys.ArrowDown)dz++;const moving=dx||dz;if(moving){const l=Math.hypot(dx,dz);dx/=l;dz/=l;player.position.x+=dx*5.2*dt;player.position.z+=dz*5.2*dt;player.rotation.y=Math.atan2(dx,dz);setAnimation('walk')}else setAnimation('idle');const desired=new THREE.Vector3(player.position.x-5.2,player.position.y+4.8,player.position.z+9);camera.position.lerp(desired,.06);camera.lookAt(player.position.x,1.55,player.position.z-1.5)}actionReady=player?player.position.distanceTo(target)<3:false;hint.textContent=actionReady?'დააჭირე E — მოქმედება':'WASD / ისრები — მოძრაობა • E — მოქმედება';renderer.render(scene,camera)}
bindControls();
loader.load('https://threejs.org/examples/models/gltf/RobotExpressive/RobotExpressive.glb',gltf=>{modelTemplate=gltf.scene;modelTemplate.traverse(o=>{if(o.isMesh){o.castShadow=o.receiveShadow=true}});player=THREE.SkeletonUtils.clone(modelTemplate);player.scale.setScalar(.85);scene.add(player);mixer=new THREE.AnimationMixer(player);idleAction=mixer.clipAction(gltf.animations.find(a=>a.name==='Idle')||gltf.animations[0]);walkAction=mixer.clipAction(gltf.animations.find(a=>a.name==='Walking')||gltf.animations[3]||gltf.animations[0]);idleAction.play();buildOutside();loading.classList.add('hide');animate()},undefined,err=>{throw new Error('3D პერსონაჟი ვერ ჩაიტვირთა: '+(err?.message||'უცნობი შეცდომა'))});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
}catch(e){loading.classList.add('hide');errorBox.textContent='3D გარემო ვერ გაიხსნა: '+e.message;errorBox.classList.add('show');console.error(e)}
})();